### ISSUE TITLE
(OPTIONAL) Email reset method.

### ISSUE THREAD

**Issue by Axirr** [CMPUT301F19T16/Sentimo#49]

**Comment by elephant98** [comment]
I works

**Comment by mariodon** [comment]
Still need UI for this

**Comment by elephant98** [comment]
Are you talking about in the app itself, because it works outside of the app with the email validation?

**Comment by mariodon** [comment]
Yeah, I used the console to send the reset email last time. There could be a password reset screen in the app where the user enters a registered email to get a password reset link.
